# Generated by Django 2.0.10 on 2019-01-28 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Produkt Nummer')),
                ('name', models.TextField(verbose_name='Name des Produktes')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=30, verbose_name='Name des Kunden')),
                ('text', models.TextField(verbose_name='Ausführliche Bewertung')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.CharField(choices=[(1, 'X'), (2, 'XX'), (3, 'XXX'), (4, 'XXXX'), (5, 'XXXXX')], max_length=1, verbose_name='Sterne')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.product')),
            ],
        ),
    ]
