# Generated by Django 2.0.10 on 2019-01-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190128_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[(1, 'X'), (2, 'XX'), (3, 'XXX'), (4, 'XXXX'), (5, 'XXXXX')], max_length=2, verbose_name='Sterne'),
        ),
    ]
