# Generated by Django 2.0.10 on 2019-02-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20190202_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(max_length=30, verbose_name='Kategorie des Inhalts')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='product_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Product'),
        ),
        migrations.AddField(
            model_name='topic',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Review'),
        ),
    ]
