# Generated by Django 2.0.10 on 2019-04-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20190418_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star4_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star5_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='prodcut',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='reviews.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Product'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Review'),
        ),
    ]
