# Generated by Django 2.0.10 on 2019-04-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20190419_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_safe',
            field=models.TextField(default='leer', max_length=33, verbose_name='HTML-sichere Version des Topics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Product'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='reviews.Product'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Review'),
        ),
    ]
